# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:15813/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

spring.flyway.enabled=false

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=UniFolioSecretKey2026VeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000

spring.jpa.open-in-view=false

# ===============================
# GOOGLE OAUTH CONFIG
# ===============================
spring.security.oauth2.client.registration.google.client-id=838055072850-9ajcv9ave6ct3a9ilpj01pq7jkutt6pt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google